import sys
import json

# https://pypi.org/project/iso3166-2/

if len(sys.argv) < 3:
    print(f"USAGE: python {sys.argv[0]} [iso json file path] [output_path]");
    exit(1);

file = sys.argv[1];
out_file_path = sys.argv[2];

iso3166_file = open(file, "r");

iso3166_json = json.load(iso3166_file);

subdivision_count = 0;
county_count = 0;

subdivisions = [];
country_codes = []

for country in iso3166_json:
    print(country);
    country_codes.append(country);
    county_count += 1;

    for subdivision in iso3166_json[country]:
        subdivision_count += 1;

        name = iso3166_json[country][subdivision].get("name");

        subdivisions.append((subdivision, name));

subdivisions_by_code = sorted(subdivisions, key=lambda t: t[0])

subdivisions_by_name = sorted(subdivisions, key=lambda t: t[1])

country_codes.sort();



out_file = open(out_file_path, "w");

out_file.write(f"// autogenerated by {sys.argv[0]} do not edit by hand\n");
out_file.write("#pragma once\n");
out_file.write("#include <array>\n");
out_file.write("#include <cstdint>\n");
out_file.write("#include <string_view>\n\n");

out_file.write("struct SubdivisionEntry {\n");
out_file.write("    std::string_view code;\n");
out_file.write("    int16_t id;\n");
out_file.write("};\n\n");

out_file.write("struct SubdivisionNameEntry {\n");
out_file.write("    std::string_view name;\n");
out_file.write("    int16_t id;\n");
out_file.write("};\n\n");

out_file.write("struct CountryEntry {\n");
out_file.write("    std::string_view code;\n");
out_file.write("    int16_t id;\n");
out_file.write("};\n\n");

out_file.write("struct SubdivisionNameCodeEntry {\n")
out_file.write("    std::string_view name;\n")
out_file.write("    std::string_view code;\n")
out_file.write("};\n\n")

out_file.write(f"static constexpr int SUBDIVISION_COUNT = {subdivision_count};\n");
out_file.write(f"static constexpr int COUNTY_COUNT      = {county_count};\n");
out_file.write(f"constexpr std::array<SubdivisionEntry, SUBDIVISION_COUNT> mappings_by_code = {{{{\n");

for i, sub in enumerate(subdivisions_by_code):
    out_file.write(f"    {{ \"{sub[0]}\", {i}}},\n");

out_file.write("}};\n\n");

out_file.write(f"constexpr std::array<const char *, SUBDIVISION_COUNT> code_mappings_by_id = {{{{\n");

for i, sub in enumerate(subdivisions_by_code):
    out_file.write(f"    \"{sub[0]}\",\n");

out_file.write("}};\n\n");


out_file.write(f"constexpr std::array<SubdivisionNameEntry, SUBDIVISION_COUNT> mappings_by_name = {{{{\n");

for i, sub in enumerate(subdivisions_by_name):
    out_file.write(f"    {{ \"{sub[1]}\", {i}}},\n");

out_file.write("}};\n\n");

out_file.write(f"constexpr std::array<const char *, SUBDIVISION_COUNT> name_mappings_by_id = {{{{\n");

for i, sub in enumerate(subdivisions_by_name):
    out_file.write(f"    \"{sub[1]}\",\n");

out_file.write("}};\n\n");

out_file.write(f"constexpr std::array<CountryEntry, COUNTY_COUNT> country_id_mappings_by_code = {{{{\n");

for i, country in enumerate(country_codes):
    out_file.write(f"    {{ \"{country}\", {i} }},\n");

out_file.write("}};\n\n");

out_file.write(f"constexpr std::array<SubdivisionNameCodeEntry, SUBDIVISION_COUNT> name_to_code_mappings = {{{{\n")
for code, name in subdivisions_by_name:
    out_file.write(f'    {{ "{name}", "{code}" }},\n')
out_file.write("}};\n\n")
